// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID       int32  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	UserName string `gorm:"column:user_name;type:character varying(191);not null" json:"user_name"`
	Password string `gorm:"column:password;type:text;not null" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
