// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangeStatus struct {
	ID        string `json:"id"`
	IsChecked bool   `json:"isChecked"`
}

type Message struct {
	Msg string `json:"msg"`
}

type Mutation struct {
}

type Query struct {
}

type Tasks struct {
	Task      string `json:"task"`
	IsChecked bool   `json:"isChecked"`
	ID        string `json:"ID"`
}

type Todo struct {
	ID    string `json:"id"`
	Tasks string `json:"tasks"`
}
