// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	Msg string `json:"msg"`
}

type Mutation struct {
}

type Query struct {
}

type Tasks struct {
	Task string `json:"task"`
}

type Todo struct {
	ID    string `json:"id"`
	Tasks string `json:"tasks"`
}
