// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID    string `json:"id"`
	Tasks string `json:"tasks"`
}
